#!/usr/bin/env python3
import argparse
import sys
import json
import yaml


def main():
    p = argparse.ArgumentParser()
    p.add_argument('source', nargs='?', type=argparse.FileType(mode='r'), default=sys.stdin)
    a = p.parse_args()

    j = yaml.load(a.source)
    json.dump(j, sys.stdout, indent=4, sort_keys=True)


if __name__ == '__main__':
    main()
